version: '3.5'

services: 
  expensetrack.database:
    image:  setrans.azurecr.io/wimc.database:0.8
    container_name: wimc.database
    environment:
      - "ACCEPT_EULA=Y"
    ports:
      - "1433:1433"